### PR TITLE
60-fix(front): Auth Modal on Auth routes

### LINKED ISSUE #60: Authorised Modal on Authorised Routes
Authorised routes can't be called if user if not signed in. So modal should be shown on call of authorised routes.

### PR DESCRIPTION
**Pull request by Kanav-Arora**
Closes #60

### CODE REVIEW

File: frontend/src/modules/ui/LoginSignupModal/LoginSignupModal.js [hunk 1]
```diff
@@ -106,8 +107,11 @@ const LoginSignupModal = ({ isVisible }) => {
                             animate={{ x: 0 }}
                             transition={{ stiffness: 120 }}
                         >
+                            <ImageOverlayText>
+                                Find Your Travel Buddy
+                            </ImageOverlayText>
                             <Image
-                                src="/images/src/kanav.webp"
+                                src="/images/fallback/AuthModal.jpg"
```
Comment (Aadi71) [inline frontend/src/modules/ui/LoginSignupModal/LoginSignupModal.js:114]: It's recommended to use webp or svg images only.

Comment (Kanav-Arora) [reply frontend/src/modules/ui/LoginSignupModal/LoginSignupModal.js:158]: We'll add it later it needs to be replaced with `<ImgwithFallback/>` component and this jpg will be converted to webp
